# Generated by Django 5.0.6 on 2024-06-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('mark_as_complete', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
